services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ragpw
      POSTGRES_DB: ragdb
    ports:
      - "5433:5432"
    volumes:
      - rag-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  rag-data: